#!/bin/bash
# Start the services!

service hello-node start
echo "Give Hello Node about 3 minutes to initialize (install Chrome)"
rm -f /tmp/hnc.log /tmp/hnc.err
nohup /opt/hello-node/bin/install-chrome.sh > /tmp/hnc.log 2> /tmp/hnc.err &
